#INITIAL SETTINGS
output_dir: "runs/Inference_MSA_Finetuning"
dataset_dir: "datasets/Inference"
model: "MSA_Finetuning"
max_length: 1024
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_MSA_Finetuning/snapshots/MSA_Finetuning.pt"



