version = 1

[[annotations]]
path = ["download_weights.job", "src/*.py", "src/*.sh", "src/models/*.py", "runs/**.sh", "runs/**.job"]
SPDX-FileCopyrightText = ["(C) 2024 Marco Celoria <celoria.marco@gmail.com>"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["runs/**.log","runs/**.diffs","runs/**.res","runs/**.png","runs/**.out","runs/**.csv","runs/**.yaml"]
SPDX-FileCopyrightText = ["(C) 2024 Marco Celoria <celoria.marco@gmail.com>"] 
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = ["(C) 2024 Marco Celoria <celoria.marco@gmail.com> and Francesca Cuturello <francesca.cuturello@areasciencepark.it>"] 
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["preprocess_data/**.py", "preprocess_data/**.sh"]
SPDX-FileCopyrightText = ["(C) 2024 Francesca Cuturello <francesca.cuturello@areasciencepark.it>"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["datasets/**", 
        "preprocess_data/**.csv","preprocess_data/check_blast_MSAs/**","preprocess_data/blastp/**","preprocess_data/README.md"]
SPDX-FileCopyrightText = ["(C) 2024 Francesca Cuturello <francesca.cuturello@areasciencepark.it>"]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["preprocess_data/scripts/reformat.pl"]
SPDX-FileCopyrightText = "(C) Johannes Soeding, 2012"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".gitignore", "requirements.txt", "REUSE.toml"]
SPDX-FileCopyrightText = ["(C) 2024 Marco Celoria <celoria.marco@gmail.com>"] 
SPDX-License-Identifier = "CC0-1.0"


