#INITIAL SETTINGS
output_dir: "runs/S1413_MSA_Finetuning_OnlyMean"
dataset_dir: "datasets/S1413"
model: "MSA_Finetuning_OnlyMean"
learning_rate: 2.0e-4
max_epochs: 20
loss_fn: "L1"
max_length: 1024
seeds: [10, 11, 12]
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1413_MSA_Finetuning_OnlyMean/snapshots/MSA_Finetuning_OnlyMean.pt"
onnx_file: "runs/S1413_MSA_Finetuning_OnlyMean/snapshots/onnx/MSA_Finetuning_OnlyMean.onnx"

