#INITIAL SETTINGS
output_dir: "runs/S157479_ESM2_Finetuning"
dataset_dir: "datasets/S157479"
model: "ESM2_Finetuning"
learning_rate: 5.0e-4
max_epochs: 20
loss_fn: "L1"
seeds: [10, 11, 12]
max_length: 1024
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S157479_ESM2_Finetuning/snapshots/ESM2_Finetuning.pt"

