#INITIAL SETTINGS
output_dir: "runs/Inference_ESM2_Finetuning"
dataset_dir: "datasets/Inference"
model: "ESM2_Finetuning"
max_length: 1024
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_ESM2_Finetuning/snapshots/ESM2_Finetuning.pt"



