#INITIAL SETTINGS
output_dir: "runs/S1465_MSA_Baseline"
dataset_dir: "datasets/S1465"
model: "MSA_Baseline"
learning_rate: 1.0e-3
max_epochs: 20
loss_fn: "L1"
max_length: 1024
seeds: [10, 11, 12]
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_MSA_Baseline/snapshots/MSA_Baseline.pt"

