#INITIAL SETTINGS
output_dir: "runs/S1465_ProstT5"
dataset_dir: "datasets/S1465"
model: "ProstT5_Finetuning"
learning_rate: 5.0e-4
max_epochs: 20
loss_fn: "L1"
seeds: [10, 11, 12]
max_length: 490
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_ProstT5/snapshots/ProstT5_Finetuning.pt"

