#INITIAL SETTINGS
output_dir: "runs/S1465_ESM2"
dataset_dir: "datasets/S1465"
model: "ESM2_Finetuning"
learning_rate: 5.0e-5
max_epochs: 20
loss_fn: "L1"
seeds: [10, 11, 12]
max_length: 1024
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_ESM2/snapshots/ESM2_Finetuning.pt"

