#INITIAL SETTINGS
output_dir: "runs/S1465_ESM2_Baseline"
dataset_dir: "datasets/S1465"
model: "ESM2_Baseline"
learning_rate: 5.0e-3
max_epochs: 20
loss_fn: "L1"
max_length: 1024
seeds: [10, 11, 12]
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S1465_ESM2_Baseline/snapshots/ESM2_Baseline.pt"
onnx_file: "runs/S1465_ESM2_Baseline/snapshots/onnx/ESM2_Baseline.onnx"


