#INITIAL SETTINGS
output_dir: "runs/S3730_MSA_Finetuning"
dataset_dir: "datasets/S3730"
model: "MSA_Finetuning"
learning_rate: 1.0e-4
max_epochs: 20
loss_fn: "L1"
seeds: [10, 11, 12]
max_length: 1024
optimizer:
  name: "AdamW"
  weight_decay: 0.01
  momentum: 0.
MSA:
  max_tokens: 16000
snapshot_file: "runs/S3730_MSA_Finetuning/snapshots/MSA_Finetuning.pt"
onnx_file: "runs/S3730_MSA_Finetuning/snapshots/onnx/MSA_Finetuning.onnx"

